// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/barathraghavan/code/rangzen/rangzen/buck-out/gen/proto-repo/compile_protobufs__srcs/RangzenMessage.proto
package org.denovogroup.rangzen.objects;

import android.util.Log;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import org.denovogroup.rangzen.backend.*;
import org.denovogroup.rangzen.backend.SecurityManager;
import org.json.JSONException;
import org.json.JSONObject;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.OPTIONAL;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * Representation of a single Rangzen message with text and priority.
 */
public final class RangzenMessage extends Message {

  public static final String DEFAULT_TEXT = "";
  public static final Double DEFAULT_PRIORITY = 0.01D;
    public static final String DEFAULT_PSEUDONYM = "";

    public static final String TEXT_KEY = "text";
    public static final String PRIORITY_KEY = "priority";
    public static final String PSEUDONYM_KEY = "pseudonym";

  /**
   * The message's text, as a String.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String text;

  /**
   * The message's priority, as a double.
   */
  @ProtoField(tag = 2, type = DOUBLE, label = REQUIRED)
  public final Double priority;

    /**
     * The message's sender name, as a String.
     */
    @ProtoField(tag = 3, type = STRING, label = OPTIONAL)
    public final String pseudonym;

  public RangzenMessage(String text, Double priority, String pseudonym) {
    this.text = text;
    this.priority = priority;
      this.pseudonym = pseudonym;
  }

    public RangzenMessage(String text, Double priority) {
        this.text = text;
        this.priority = priority;
        this.pseudonym = "";
    }

  private RangzenMessage(Builder builder) {
    this(builder.text, builder.priority, builder.pseudonym);
    setBuilder(builder);
  }

    public static RangzenMessage fromJSON(JSONObject json){
        return new RangzenMessage(
                json.optString(TEXT_KEY, DEFAULT_TEXT),
                json.optDouble(PRIORITY_KEY, DEFAULT_PRIORITY),
                json.optString(PSEUDONYM_KEY, DEFAULT_PSEUDONYM)
                );
                //TODO opt location
    }

    public static RangzenMessage fromJSON(String jsonString){
        JSONObject json;
        try {
            json = new JSONObject(jsonString);
        } catch (JSONException e) {
            e.printStackTrace();
            json = new JSONObject();
        }
        return fromJSON(json);
    }

    /** convert the message into a json object using the supplied security profile restrictions */
    public JSONObject toJSON(int securityProfile){
        JSONObject result = new JSONObject();
        try {
            result.put(TEXT_KEY, this.text);
            result.put(PRIORITY_KEY, this.priority + Utils.makeNoise(0d, 0.003d));

            SecurityProfile profile = SecurityManager.getProfile(securityProfile);

            //put optional items based on security profile settings
            if(profile.isPseudonyms()) result.put(PSEUDONYM_KEY, this.pseudonym);
            //if(profile.isShareLocation()) result.put(TEXT_KEY, this.location); //TODO location

        } catch (JSONException e) {
            e.printStackTrace();
        }
        return result;
    }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RangzenMessage)) return false;
    RangzenMessage o = (RangzenMessage) other;
    return equals(text, o.text)
        && equals(priority, o.priority);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = text != null ? text.hashCode() : 0;
      result = result * 37 + (priority != null ? priority.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RangzenMessage> {

    public String text;
    public Double priority;
      public String pseudonym;

    public Builder() {
    }

    public Builder(RangzenMessage message) {
      super(message);
      if (message == null) return;
      this.text = message.text;
      this.priority = message.priority;
      this.pseudonym = message.pseudonym;
    }

    /**
     * The message's text, as a String.
     */
    public Builder text(String text) {
      this.text = text;
      return this;
    }

    /**
     * The message's priority, as a double.
     */
    public Builder priority(Double priority) {
      this.priority = priority;
      return this;
    }

      /**
       * The message's sender name, as a string.
       */
      public Builder pseudonym(String pseudonym) {
          this.pseudonym = pseudonym;
          return this;
      }

    @Override
    public RangzenMessage build() {
      checkRequiredFields();
      return new RangzenMessage(this);
    }
  }
}
